version: "3.3"
services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust